config/routes.rb
Jqueryblog::Application.routes.draw do
  resources :cards

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  resources :orders
  root :to => 'orders#new'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fidecard Pagos</title>
  <%= stylesheet_link_tag "application"%>
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.min.css" />  
  <link rel="stylesheet" href="http://jeromeetienne.github.com/jquery-mobile-960/css/jquery-mobile-960.min.css" />
  <%= javascript_include_tag 'jquery','rails','jquery.keypad.min' %>  
<script type="text/javascript"> 
     jQuery(document).bind("mobileinit", function(){jQuery.extend(  jQuery.mobile , {ajaxFormsEnabled : false});});
    </script> 
    <script type="text/javascript" src="http://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.min.js"></script> 
    <script>
       $(document).ready(function(){
      //  Focus auto-focus fields
      $('.auto-focus:first').focus();});
    $(function () {
      $('#order_amount').keypad( {keyclass:'midnightKeypad',layout: ['789' + $.keypad.CLOSE,'456' + $.keypad.CLEAR,'123' + $.keypad.BACK,'.0' ]});
      $('#order_card_verification').keypad();
    });
    </script>
  <%= csrf_meta_tag %>
</head>
  <body>
    <div data-role="page" data-theme="b">
      <div data-role="header">
     <h1><%= content_for?(:title) ? yield(:title) : "Untitled" %> </h1>
        <% if logged_in? %>
          <div align="center">Bienvenido <%= current_user.nombre %></div>  
       <%= link_to "Ver Perfil", edit_current_user_path %>
    <%= link_to "Salir", logout_path ,"class" => "ui-btn-right" %>
   <% else %>
     <%= link_to "Crear Usuario", signup_path %>
     <%= link_to "Ingresar", login_path ,"class" => "ui-btn-right"%>
   <% end %>
 </div>
 <%= image_tag "encabezado_1.jpg", :width=>'960'%>
   <div data-role="content">
         <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}",:class => "ui-body ui-body-e" %>
      <% end %>
      <%= yield %>
      </div>
            <div data-role="footer">
        <% if logged_in? %>
          <h4><%= current_user.comercio%></h4>
        <% else%>
          <h4>Fidecard Pagos</h4>
        <% end%>
      </div><!-- /footer -->
    </div>
  </body>
</html>
  